### ISSUE TITLE
Vscode fails to open the repo container

### ISSUE THREAD

**Issue by mhmcvay** [ChicoState/Shoe-Expert#31]

**Comment by Kapral67** [comment]
Can you post your dev-container log?

**Comment by mhmcvay** [comment]
Command failed: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /workspaces/Shoe-Expert --workspace-mount-consistency cached --id-label vsch.local.repository=https://github.com/ChicoState/Shoe-Expert.git/tree/main --id-label vsch.local.repository.volume=Shoe-Expert-main-8b2a7a8333942805b5376fc518ba335f --id-label vsch.local.repository.folder=Shoe-Expert --log-level debug --log-format json --config /workspaces/Shoe-Expert/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-6f600194-5609-43db-a403-4c91f584d28f.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=Shoe-Expert-main-8b2a7a8333942805b5376fc518ba335f,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root true --terminal-columns 96 --terminal-rows 13

**Comment by Kapral67** [comment]
@mhmcvay How did you fix this?
